"""add preferred_skills and fk to job_analyses

Revision ID: 41b3e6b2ea87
Revises: f26f4ed7d12c
Create Date: 2026-07-20 12:21:55.457600

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '41b3e6b2ea87'
down_revision: Union[str, Sequence[str], None] = 'f26f4ed7d12c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job_analyses', sa.Column('preferred_skills', sa.ARRAY(sa.String()), nullable=False))
    op.create_unique_constraint('uq_job_analyses_job_id', 'job_analyses', ['job_id'])
    op.create_foreign_key(
        'fk_job_analyses_job_id', 
        'job_analyses', 'jobs', 
        ['job_id'], ['id']
    )

    # ### end Alembic commands ###



def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('job_analyses', 'preferred_skills')
    # ### end Alembic commands ###
