"""add analysis column to job_matches

Revision ID: d7376ee663e3
Revises: d26154dbbe46
Create Date: 2026-07-17 21:17:28.507512

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd7376ee663e3'
down_revision: Union[str, Sequence[str], None] = 'd26154dbbe46'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job_matches', sa.Column('analysis', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('job_matches', 'analysis')
    # ### end Alembic commands ###

