"""create job_analyses table

Revision ID: f26f4ed7d12c
Revises: d7376ee663e3
Create Date: 2026-07-20 12:18:49.827915

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f26f4ed7d12c'
down_revision: Union[str, Sequence[str], None] = 'd7376ee663e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_analyses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('required_skills', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('seniority', sa.String(), nullable=True),
    sa.Column('min_years_experience', sa.Integer(), nullable=True),
    sa.Column('responsibilities', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('ats_keywords', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('raw_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('analyzed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('job_analyses')
    # ### end Alembic commands ###
